Arrival time lag metric
iotaledger-archive/cliri pull request #123
Opened 2019-04-16 15:16 UTC by alongalky

Addresses the first half of #122, solidification timestamp lag is pending #120

2019-04-17 17:22 UTC, alon-e requested changes

2019-04-17 17:22 UTC, alon-e commented on src/main/java/com/iota/iri/service/dto/GetNodeInfoResponse.java
> +        res.features = features;
please follow indentation in file.

2019-04-17 17:22 UTC, alon-e commented on src/main/java/com/iota/iri/service/dto/GetNodeInfoResponse.java
> +                                  int numberOfTransactionsToRequest, String[] features,
please follow indentation in file.

2019-04-17 17:22 UTC, alon-e commented on src/main/java/com/iota/iri/service/tipselection/impl/ConnectedComponentsStartingTipSelector.java
> -        return tipsInLargestComponent.get(random.nextInt(tipsInLargestComponent.size()));
so how do you select a tip in the largest component?
i.e. did you mean to remove the part that intersects w/ tips?

2019-04-17 17:22 UTC, alon-e commented on src/main/java/com/iota/iri/service/tipselection/impl/ConnectedComponentsStartingTipSelector.java
> +    private Hash randomlySelectTransactionFromLargestConnectedComponent(Collection<Set<Hash>> connectedComponents) {
why do you select a random transaction and not a random tip? Do you want to minimize the number of steps backwards?
does this hurt the assumptions in any way?

2019-04-17 17:22 UTC, alon-e commented on src/main/java/com/iota/iri/service/stats/LagCalculator.java
> +          int middle = lags.length/2;
```suggestion
          int middle = lags.length / 2;
```

2019-04-17 17:22 UTC, alon-e commented on src/main/java/com/iota/iri/service/API.java
> +                instance.lagCalculator.getMedianArrivalLag()
we should be aware that this is not O(1), but the rest of this call is; `getNodeInfo` is often used as a heartbeat and should return very fast.

I don't have a proposal on how to solve this, maybe having `lagCalculator` run a thread that calculates this metric every once in a while and answers the get in O(1).

2019-04-22 11:21 UTC, alongalky commented on src/main/java/com/iota/iri/service/tipselection/impl/ConnectedComponentsStartingTipSelector.java
> +    private Hash randomlySelectTransactionFromLargestConnectedComponent(Collection<Set<Hash>> connectedComponents) {
Because it simplifies the code, no need to find the intersection of tips and recent txs. Moreover the tips we get from `TipsViewModel` are based on the FIFO structure and may not actually be very recent from a `solidificationTimestamp` POV, so to make we reach a tip in the largest component I think it would make sense to run another BFS, which again complicates the code (IMO) needlessly. I don't see why it matters if we start backtracking from a tip or anywhere else in the largest component.

2019-04-22 11:21 UTC, alongalky commented on src/main/java/com/iota/iri/service/API.java
> +                instance.lagCalculator.getMedianArrivalLag()
True. I think a thread is overkill at this stage though, let's optimize if we see it's slow. There is also some justification: while it's not O(1), it's O(100) or so, there is no heavy lifting being done.

2019-04-22 11:21 UTC, alongalky commented on src/main/java/com/iota/iri/service/dto/GetNodeInfoResponse.java
> +                                  int numberOfTransactionsToRequest, String[] features,
It looks the same on my machine, apparently the repo uses tabs instead of spaces.

![tabsvsspaces](https://user-images.githubusercontent.com/13794950/56490348-987f0a00-64ed-11e9-93cd-a034490cfde1.gif)

2019-04-22 11:25 UTC, alon-e commented on src/main/java/com/iota/iri/service/tipselection/impl/ConnectedComponentsStartingTipSelector.java
> +    private Hash randomlySelectTransactionFromLargestConnectedComponent(Collection<Set<Hash>> connectedComponents) {
I agree, but wanted to make sure this was an intentional change - the "if we start backtracking from a tip or anywhere else in the largest component." part.

2019-04-22 11:26 UTC, alon-e commented on src/main/java/com/iota/iri/service/API.java
> +                instance.lagCalculator.getMedianArrivalLag()
>there is no heavy lifting being done.
we have the sorted heap part that may be an issue, but I agree that we can address it in the future if needed.

2019-04-22 11:26 UTC, alon-e approved these changes

2019-04-22 13:41 UTC, merged