Cumulative weight based entry point selector
iotaledger-archive/cliri pull request #51
Opened 2018-12-02 16:00 UTC by alongalky

Fixes #50

2018-12-03 13:27 UTC, alon-e requested changes

2018-12-03 13:27 UTC, alon-e commented on src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorCumulativeWeightThreshold.java
> +    private final CumulativeWeightCalculator cumulativeWeightCalculator;
why not use the interface `RatingCalculator`?

2018-12-03 13:27 UTC, alon-e commented on src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorCumulativeWeightThreshold.java
> +        // Stop when reaching the genesis or the cumulative weight threshold
this doc line is confusing - it's inverted from what is actually written in the code.

2018-12-03 13:27 UTC, alon-e commented on src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorCumulativeWeightThreshold.java
> +            currentWeight = cumulativeWeightCalculator.calculate(currentHash).get(currentHash);
I think this method should use the simplified version of CW calculation - via b/dfs. the method used assumes you would use all intermediate values.

my proposal is to add a method (to the `RatingCalculator` interface)  that returns the weight of a transaction - and runs the simplified version.

2018-12-03 13:27 UTC, alon-e commented on src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorCumulativeWeightThresholdTest.java
> +        Assert.assertEquals(Hash.NULL_HASH, entryPoint);
I don't get how this returns Genesis -- your tip does not point to Genesis, I think it had to do w/ a bug that when a `TxVM.fromHash(UNKOWN_TX)` returns all-9

2018-12-03 14:48 UTC, alongalky commented on src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorCumulativeWeightThresholdTest.java
> +        Assert.assertEquals(Hash.NULL_HASH, entryPoint);
I'll correct the test

2018-12-03 15:15 UTC, alongalky commented on src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorCumulativeWeightThreshold.java
> +        // Stop when reaching the genesis or the cumulative weight threshold
Changed to `Backtrack as long as the genesis hasn't been reached and the tresholed has not been crossed`

2018-12-03 15:17 UTC, alongalky commented on src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorCumulativeWeightThreshold.java
> +    private final CumulativeWeightCalculator cumulativeWeightCalculator;
I don't want a generic rating (with LM / stars / whatever), I want CW specifically

2018-12-04 10:29 UTC, alon-e approved these changes

2018-12-04 10:29 UTC, merged